### ISSUE TITLE
Please add valid tags for versioning

### ISSUE THREAD

**Issue by chbeer** [TheiPhoneDev/UpdateKit#1]
See:

https://developer.apple.com/documentation/xcode/publishing-a-swift-package-with-xcode#Tag-your-latest-commit

**Comment by chbeer** [comment]
<img width="465" alt="image" src="https://github.com/user-attachments/assets/2bb12833-a6e7-4331-8aa8-ddebd7902444">

**Comment by TheiPhoneDev** [comment]
Thank you Christian, gonna work on that!

**Comment by TheiPhoneDev** [comment]
> <img alt="image" width="465" src="https://private-user-images.githubusercontent.com/121761/379545975-2bb12833-a6e7-4331-8aa8-ddebd7902444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODU0MjYsIm5iZiI6MTcyOTc4NTEyNiwicGF0aCI6Ii8xMjE3NjEvMzc5NTQ1OTc1LTJiYjEyODMzLWE2ZTctNDMzMS04YWE4LWRkZWJkNzkwMjQ0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxNTUyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWExMzVlYTNjMjRhNTkxN2U0NTQwZGFiYTE5YWE3MDhkZmFjNjM0OGJmYzk4OThiNjRhMzU5MjVkYmMzOTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8dMGtm_MWy86FBJvha1ONPt7EYv0KEmq136j5_0j4ns">

Hi Christian, I think that valid tags for versioning should now work. Let me know! If everything works, I'll close the issue.
